name: kametibook
description: KametiBook mobile app for managing local kameti committee groups.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.6.0
  connectivity_plus: ^7.1.1
  firebase_auth: ^6.5.3
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.0
  firebase_storage: ^13.4.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  image_picker: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.6
  pdf: ^3.12.0
  printing: ^5.14.3
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
