import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../../core/utils/date_formatter.dart';
import '../models/report_model.dart';

class ReportPdfService {
  static Future<String> exportReportToPdf(ReportData data) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (context) => [
          pw.Header(level: 0, child: pw.Text('KametiBook', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold))),
          pw.Text(data.model.title, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.Text(data.kametiName),
          pw.Text('Generated: ${DateFormatter.display(data.model.generatedAt)}'),
          pw.SizedBox(height: 14),
          pw.Text('Summary', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          pw.TableHelper.fromTextArray(
            headers: const ['Metric', 'Value'],
            data: data.summaryCards.entries.map((entry) => [entry.key, entry.value]).toList(),
          ),
          if (data.warnings.isNotEmpty) ...[
            pw.SizedBox(height: 12),
            pw.Text('Warnings', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            ...data.warnings.map((warning) => pw.Bullet(text: warning)),
          ],
          for (final section in data.sections) ...[
            pw.SizedBox(height: 14),
            pw.Text(section.title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            if (section.rows.isEmpty)
              pw.Text('No records.')
            else
              pw.TableHelper.fromTextArray(
                headers: section.rows.first,
                data: section.rows.skip(1).toList(),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8),
                cellStyle: const pw.TextStyle(fontSize: 8),
                cellAlignment: pw.Alignment.centerLeft,
              ),
          ],
          pw.SizedBox(height: 16),
          pw.Divider(),
          pw.Text('Generated by KametiBook'),
          pw.Text(
            'This report is generated by KametiBook for personal record-keeping only. KametiBook is not a bank, financial institution, or legal authority. Please verify all records with group members.',
            style: const pw.TextStyle(fontSize: 8),
          ),
        ],
        footer: (context) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8)),
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final fileName = '${_sanitize(data.model.title)}_${_sanitize(data.kametiName)}.pdf';
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }

  static Future<void> shareReportPdf(String filePath, {String? text}) async {
    await SharePlus.instance.share(ShareParams(files: [XFile(filePath)], text: text));
  }

  static Future<void> shareReportSummary(String summary) async {
    await SharePlus.instance.share(ShareParams(text: summary));
  }

  static String _sanitize(String input) {
    return input.replaceAll(RegExp(r'[^A-Za-z0-9]+'), '_').replaceAll(RegExp(r'_+'), '_');
  }
}
